<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<WindowsSdkPackageVersion>10.0.26100.73-preview</WindowsSdkPackageVersion>
		<Nullable>annotations</Nullable>
		<UseUwp>true</UseUwp>
		<Platforms>x64;ARM64</Platforms>
		<DefaultLanguage>zh-CN</DefaultLanguage>
		<IsAotCompatible>true</IsAotCompatible>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
		<RootNamespace>DanmakuFrostMaster</RootNamespace>
		<AssemblyName>DanmakuFrostMaster</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Win2D.uwp" Version="1.28.2" />
	</ItemGroup>
</Project>