<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<WindowsSdkPackageVersion>10.0.26100.73-preview</WindowsSdkPackageVersion>
		<Nullable>enable</Nullable>
		<UseUwp>true</UseUwp>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<DefaultLanguage>zh-CN</DefaultLanguage>
		<PublishAot>true</PublishAot>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
		<EnableMsixTooling>true</EnableMsixTooling>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Properties\**" />
	  <EmbeddedResource Remove="Properties\**" />
	  <None Remove="Properties\**" />
	  <Page Remove="Properties\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="DemoFiles\demo_2.mp4" />
		<None Remove="DemoFiles\demo_2_danmaku.xml" />
		<None Remove="DemoFiles\demo_3.mp4" />
		<None Remove="DemoFiles\demo_3_danmaku.xml" />
		<None Remove="DemoFiles\demo_3_en-us.sub" />
		<None Remove="DemoFiles\demo_3_ja-jp.sub" />
		<None Remove="DemoFiles\demo_3_zh-t.sub" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="DemoFiles\demo_2.mp4" />
		<Content Include="DemoFiles\demo_2_danmaku.xml" />
		<Content Include="DemoFiles\demo_3.mp4" />
		<Content Include="DemoFiles\demo_3_danmaku.xml" />
		<Content Include="DemoFiles\demo_3_en-us.sub" />
		<Content Include="DemoFiles\demo_3_ja-jp.sub" />
		<Content Include="DemoFiles\demo_3_zh-t.sub" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\DanmakuFrostMaster\DanmakuFrostMaster.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <PRIResource Remove="Properties\**" />
	</ItemGroup>
</Project>